### Import Libraries

In [3]:
import pandas as pd
import numpy as np

### Load Data

In [4]:
df = pd.read_csv("movies_dataset.csv")

### Display first 5 rows

In [5]:
df.head(5)

,Unnamed: 0,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"['Drama', 'Crime']",278,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,175.407,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.700,27572
1,1,False,/tmU7GeKVybMWFButWEGl2M4GeiP.jpg,"['Drama', 'Crime']",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",201.059,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.689,20919
2,2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"['Drama', 'Crime']",240,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,102.946,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.600,12620
3,3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"['Drama', 'History', 'War']",424,en,Schindler's List,The true story of how businessman Oskar Schind...,136.953,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.567,16063
4,4,False,/bxgTSUenZDHNFerQ1whRKplrMKF.jpg,['Drama'],389,en,12 Angry Men,The defense and the prosecution have rested an...,74.742,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,1957-04-10,12 Angry Men,False,8.500,8812

In [6]:
df.columns

Index(['Unnamed: 0', 'adult', 'backdrop_path', 'genre_ids', 'id',
       'original_language', 'original_title', 'overview', 'popularity',
       'poster_path', 'release_date', 'title', 'video', 'vote_average',
       'vote_count'],
      dtype='str')

### Clean Data

In [7]:
df = df[["title", "overview", "poster_path", "vote_average", "release_date"]]
df.isna().sum()

title           0
overview        0
poster_path     7
vote_average    0
release_date    2
dtype: int64

In [8]:
df["vote_average"] = df["vote_average"].fillna(
    df["vote_average"].mean()
)

df["overview"] = df["overview"].fillna("")
df["poster_path"] = df["poster_path"].fillna("")
df["release_date"] = df["release_date"].fillna("")

In [9]:
df["vote_average"] = df["vote_average"].fillna(df["vote_average"].mean())

In [10]:
df.isna().sum()

title           0
overview        0
poster_path     0
vote_average    0
release_date    0
dtype: int64

In [11]:
df.fillna("",inplace=True)

,title,overview,poster_path,vote_average,release_date
0,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,8.700,1994-09-23
1,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,8.689,1972-03-14
2,The Godfather Part II,In the continuing saga of the Corleone crime f...,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,8.600,1974-12-20
3,Schindler's List,The true story of how businessman Oskar Schind...,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,8.567,1993-12-15
4,12 Angry Men,The defense and the prosecution have rested an...,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,8.500,1957-04-10
...,...,...,...,...,...
9910,Alone in the Dark,Edward Carnby is a private investigator specia...,/bSxrbVCyWW077zhtpuYlo3zgyug.jpg,3.234,2005-01-28
9911,Disaster Movie,"Over the course of one evening, an unsuspectin...",/22KcSCbpdAo3bhIsIiKJ1KomM9x.jpg,3.200,2008-08-29
9912,House of the Dead,"Set on an island off the coast, a techno rave ...",/lI6UBnxwHztggSq8PhLibdOe2Nd.jpg,3.131,2003-04-11
9913,Dragonball Evolution,"On his 18th birthday, Goku receives a mystical...",/ztlqrY7VgFIFmtzVsh3TPYiXCdF.jpg,2.900,2009-03-12
9914,Birdemic: Shock and Terror,A platoon of eagles and vultures attacks the r...,/gqmcAVNNUosB55RliecFYnkWT4M.jpg,2.173,2010-02-27

In [12]:
df.isna().sum()

title           0
overview        0
poster_path     0
vote_average    0
release_date    0
dtype: int64

In [13]:
df.drop_duplicates()

,title,overview,poster_path,vote_average,release_date
0,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,8.700,1994-09-23
1,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,8.689,1972-03-14
2,The Godfather Part II,In the continuing saga of the Corleone crime f...,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,8.600,1974-12-20
3,Schindler's List,The true story of how businessman Oskar Schind...,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,8.567,1993-12-15
4,12 Angry Men,The defense and the prosecution have rested an...,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,8.500,1957-04-10
...,...,...,...,...,...
9910,Alone in the Dark,Edward Carnby is a private investigator specia...,/bSxrbVCyWW077zhtpuYlo3zgyug.jpg,3.234,2005-01-28
9911,Disaster Movie,"Over the course of one evening, an unsuspectin...",/22KcSCbpdAo3bhIsIiKJ1KomM9x.jpg,3.200,2008-08-29
9912,House of the Dead,"Set on an island off the coast, a techno rave ...",/lI6UBnxwHztggSq8PhLibdOe2Nd.jpg,3.131,2003-04-11
9913,Dragonball Evolution,"On his 18th birthday, Goku receives a mystical...",/ztlqrY7VgFIFmtzVsh3TPYiXCdF.jpg,2.900,2009-03-12
9914,Birdemic: Shock and Terror,A platoon of eagles and vultures attacks the r...,/gqmcAVNNUosB55RliecFYnkWT4M.jpg,2.173,2010-02-27

In [14]:
df['combined'] = (
    df['title'] + " " +
    df['overview']
)

In [15]:
df['combined']

0       The Shawshank Redemption Imprisoned in the 194...
1       The Godfather Spanning the years 1945 to 1955,...
2       The Godfather Part II In the continuing saga o...
3       Schindler's List The true story of how busines...
4       12 Angry Men The defense and the prosecution h...
                              ...
9910    Alone in the Dark Edward Carnby is a private i...
9911    Disaster Movie Over the course of one evening,...
9912    House of the Dead Set on an island off the coa...
9913    Dragonball Evolution On his 18th birthday, Gok...
9914    Birdemic: Shock and Terror A platoon of eagles...
Name: combined, Length: 9915, dtype: str

### Convert text into numbers

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
vectorizer = TfidfVectorizer(stop_words='english')
matrix = vectorizer.fit_transform(df['combined'])

In [17]:
similarity  =  cosine_similarity(matrix)
similarity

array([[1.        , 0.00439293, 0.00480986, ..., 0.        , 0.        ,
        0.        ],
       [0.00439293, 1.        , 0.45546898, ..., 0.        , 0.        ,
        0.        ],
       [0.00480986, 0.45546898, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.01996782],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.01996782, 0.        ,
        1.        ]], shape=(9915, 9915))

In [18]:
def recommend(movie_name):

    movie_name = movie_name.lower().strip()

    if movie_name not in df["title"].str.lower().values:
        return "Movie not found"

    idx = df[df["title"].str.lower() == movie_name].index[0]

    scores = list(enumerate(similarity[idx]))

    scores = sorted(
        scores,
        key=lambda x: x[1],
        reverse=True
    )[1:6]

    recommendations = []

    for i in scores:

        movie = df.iloc[i[0]]

        recommendations.append({
            "title": movie["title"],
            "rating": movie["vote_average"],
            "poster_path": movie["poster_path"]
        })

    return recommendations

In [19]:
user_input = input("Enter movie name").title()

In [20]:
user_input

'The Poison Rose'

In [21]:
user_input = user_input.replace("'",'')
user_input

'The Poison Rose'

In [22]:
recommend(user_input)

[{'title': 'Bodies Bodies Bodies',
  'rating': np.float64(6.203),
  'poster_path': '/hSuTjDmqRdy7Dii8ymnF2WILTeP.jpg'},
 {'title': 'Primal Fear',
  'rating': np.float64(7.7),
  'poster_path': '/qJf2TzE8nRTFbFMPJNW6c8mI0KU.jpg'},
 {'title': 'Luck',
  'rating': np.float64(7.8),
  'poster_path': '/9OpVlfJGNvX3lUqdzY0nGoA6wQa.jpg'},
 {'title': 'Life of Pi',
  'rating': np.float64(7.403),
  'poster_path': '/iLgRu4hhSr6V1uManX6ukDriiSc.jpg'},
 {'title': 'Manhattan Murder Mystery',
  'rating': np.float64(7.274),
  'poster_path': '/axriUXXcBVZMZT8I9boo07Jgptw.jpg'}]

In [27]:
import pickle
# Reduce memory usage
similarity = similarity.astype("float32")
with open("movie_data.pkl", "wb") as file:
    pickle.dump((df, similarity), file)

In [28]:
print(df.shape)
print(similarity.shape)
print(type(similarity))

(9915, 6)
(9915, 9915)
<class 'numpy.ndarray'>

In [29]:
print(similarity.dtype)
print(similarity.nbytes / (1024 ** 2), "MB")

float32
375.01230239868164 MB